sudo: true
language: java
script: bin/kaocha
install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
  - chmod +x linux-install-1.10.1.536.sh
  - sudo ./linux-install-1.10.1.536.sh
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gitlibs
    - .cpcache
